/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paperB;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tenusha
 */
public class add extends javax.swing.JFrame {
    
    
     
    dataAccess d;
    /**
     * Creates new form add
     */
    public add() throws ClassNotFoundException, SQLException{
        initComponents();
        
        d=new dataAccess();
        d.dbcon(); 
        
        setdate();
        
        fillManufacturers();
        
       
    }
    void setdate(){
     DateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS");
        Date d = new Date();
       date.setText(df.format(d));
       
    
    
    }
    
    void fillManufacturers() throws SQLException{
        ResultSet rs=d.getManufactures();
        
        manufacturer.removeAllItems();
        
        while(rs.next()){
            manufacturer.addItem(rs.getString("man_id"));
        }
        manufacturer.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wood = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        manufacturer = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        success = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        modelno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(wood, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 177, 25));
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 177, 25));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 177, 25));

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        manufacturer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yamaha", "Schweighofer", "Wertheim", "Steinway & Sons" }));
        manufacturer.setSelectedIndex(-1);
        getContentPane().add(manufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 11, 177, 30));

        jLabel1.setText("manufacturer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 85, 30));

        jLabel2.setText("modelName");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 85, 25));

        jLabel3.setText("price");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 85, 25));

        jLabel5.setText("Added date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 85, 25));

        jLabel6.setText("quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 85, 25));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 177, 25));

        success.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(success, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 232, 140, 23));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 177, 25));

        jLabel7.setText("wood");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 85, 25));

        jLabel4.setText("Model No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        getContentPane().add(modelno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 180, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            this.dispose();
            
            new search().setVisible(true);
           
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int man=Integer.parseInt((String) manufacturer.getSelectedItem());
        System.out.println(man);
        int mo = Integer.parseInt(modelno.getText());
        if(d.addPiano(mo,man,wood.getText(),price.getText(),Integer.parseInt(qty.getText()),date.getText(),name.getText())){
           
            success.setForeground(Color.GREEN);
            success.setText("Piano Successfully added");
        }
        else{
           success.setForeground(Color.RED);
            success.setText("Failed to add");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new add().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(add.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(add.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> manufacturer;
    private javax.swing.JTextField modelno;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField qty;
    private javax.swing.JLabel success;
    private javax.swing.JTextField wood;
    // End of variables declaration//GEN-END:variables
}
